# Generated by Django 5.0.4 on 2024-04-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('telfone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
