# Generated by Django 5.0.4 on 2024-04-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='telfone',
            new_name='telefone',
        ),
    ]
